import type { TeamMember } from './types'

export const MOCK_TEAM: TeamMember[] = [
  {
    id: 'harishan-ambhihaipahan',
    name: 'Harishan Ambhihaipahan',
    role: 'Student Builder Group Leader',
    faculty: 'University of Sri Jayewardenepura',
    bio: 'Leading AWS Student Builder Group USJ. Spearheading cloud community initiatives, builder workshops, industry partnerships, and student developer enablement across the university.',
    certifications: ['AWS Certified Solutions Architect', 'AWS Builder Leader'],
    linkedin: 'https://linkedin.com',
  },
  {
    id: 'waruna-udara',
    name: 'Waruna Udara',
    role: 'Event & Logistics Lead',
    faculty: 'Faculty of Applied Sciences / Computing',
    bio: 'Overseeing technical meetups, hands-on workshop logistics, hackathons, and operational venue management for AWS SBG USJ builder sessions.',
    certifications: ['AWS Certified Solutions Architect', 'AWS Certified Cloud Practitioner'],
    github: 'https://github.com/WarunaUdara',
    linkedin: 'https://linkedin.com/in/warunaudara',
  },
  {
    id: 'eranga',
    name: 'Eranga',
    role: 'Technical Lead',
    faculty: 'Faculty of Computing / Technology',
    bio: 'Architecting hands-on workshop technical labs, cloud code repositories, and guiding student builders through serverless, DevOps, and Amazon Bedrock architectures.',
    certifications: ['AWS Certified Developer Associate', 'AWS Solutions Architect'],
    github: 'https://github.com',
    linkedin: 'https://linkedin.com',
  },
  {
    id: 'vaseegaran',
    name: 'Vaseegaran',
    role: 'Community & Outreach Lead',
    faculty: 'Faculty of Applied Sciences',
    bio: 'Driving campus engagement, inter-faculty collaborations, student outreach, and connecting USJ builders with the wider AWS community across Sri Lanka.',
    certifications: ['AWS Community Builder', 'AWS Cloud Quest'],
    linkedin: 'https://linkedin.com',
  },
  {
    id: 'vishishta',
    name: 'Vishishta',
    role: 'Media & Communication Lead',
    faculty: 'Faculty of Humanities & Social Sciences',
    bio: 'Managing brand communications, creative digital media, event coverage, and storytelling across digital channels for the USJ builder community.',
    certifications: ['AWS Cloud Practitioner'],
    linkedin: 'https://linkedin.com',
  },
  {
    id: 'karthigan',
    name: 'Karthigan',
    role: 'Operations & Strategy Lead',
    faculty: 'Faculty of Management Studies / Computing',
    bio: 'Directing strategic initiatives, operational frameworks, and event execution timelines to deliver scalable learning experiences for members.',
    certifications: ['AWS Cloud Quest Solutions'],
    linkedin: 'https://linkedin.com',
  },
  {
    id: 'kushalini',
    name: 'Kushalini',
    role: 'Operations & Strategy Lead',
    faculty: 'Faculty of Technology / Computing',
    bio: 'Co-directing operational planning, student builder onboarding pipelines, and resource coordination to power community activities across campus.',
    certifications: ['AWS Cloud Practitioner'],
    linkedin: 'https://linkedin.com',
  },
]
